[server.capabilities]
dereferencing = true
iri_mapping = false # "iri"
recipient_merging = false

# dereferencing.authz = false
### C2S
c2s.default = false
# c2s.outbox.default = true
# c2s.outbox.get = true
c2s.outbox.post.default = true
c2s.outbox.post.Create = false
c2s.outbox.post.Update.default = false
c2s.outbox.post.Update.partial = false
c2s.outbox.post.Delete = false
c2s.outbox.post.Follow = true
c2s.outbox.post.Add = false
c2s.outbox.post.Remove = false
c2s.outbox.post.Like = false
c2s.outbox.post.Block = false
c2s.outbox.post.Undo.default = false
c2s.outbox.post.Undo.Follow = false

### S2S
s2s.default = false
s2s.inbox.default = false
s2s.inbox.get = true
s2s.inbox.post.default = true
s2s.inbox.post.Create = true
# s2s.inbox.post.Update = false
# s2s.inbox.post.Delete = false
s2s.inbox.post.Follow = true
# s2s.inbox.post.Accept.default = false
s2s.inbox.post.Accept.Follow = true
# s2s.inbox.post.Reject.default = false
s2s.inbox.post.Reject.Follow = true
# s2s.inbox.post.Add = false
# s2s.inbox.post.Remove = false
# s2s.inbox.post.Like = false
# s2s.inbox.post.Announce = false
# s2s.inbox.post.Undo.default = false
s2s.inbox.post.Undo.Follow = true
# s2s.inbox.shared = true

### Collections support - both spec'ed and custom
collections.default = false
# collections.liked = false
collections.followers = true
collections.following = true
# collections.custom = false

### Other AP featuress
# tombstones = true
# Some AP servers don't support standard audience processing
audience = false

### Other non-AP features
webfinger = true
nodeinfo = true
x-nodeinfo2 = false
host-meta = false
portable_contacts = false # poco
robots_txt = false

#
# Test-specific Configurations
#

# [test_assumes_default_context]
# xfail = "Server exception"
# bug = true