[server.capabilities]
dereferencing = true
iri_mapping = false # "iri"
audience.authorization = true

# dereferencing.authz = false
### C2S
c2s.default = false
# c2s.outbox.default = true
c2s.outbox.get = true
c2s.outbox.post.default = true
c2s.outbox.post.Create = true
c2s.outbox.post.Update.default = false
c2s.outbox.post.Update.partial = false
c2s.outbox.post.Delete = true
c2s.outbox.post.Follow = true
c2s.outbox.post.Add = true
c2s.outbox.post.Remove = true
c2s.outbox.post.Like = true
c2s.outbox.post.Block = true
c2s.outbox.post.Undo.default = true
c2s.outbox.post.Undo.Follow = true
c2s.outbox.post.Undo.Like = true

c2s.outbox.post.multityped = true
c2s.outbox.post.delivery.local = true
c2s.outbox.post.delivery.remote = true

c2s.collections.custom = true
# c2s.collections.liked = true

# c2s.recipient_merging = true
c2s.audience.delivery = false


### S2S
s2s.default = false
s2s.inbox.default = false
s2s.inbox.get = true
s2s.inbox.post.default = true
s2s.inbox.post.Create = true
# s2s.inbox.post.Update = false
# s2s.inbox.post.Delete = false
s2s.inbox.post.Follow = true
# s2s.inbox.post.Accept.default = false
s2s.inbox.post.Accept.Follow = true
# s2s.inbox.post.Reject.default = false
s2s.inbox.post.Reject.Follow = true
# s2s.inbox.post.Add = false
# s2s.inbox.post.Remove = false
# s2s.inbox.post.Like = false
# s2s.inbox.post.Announce = false
# s2s.inbox.post.Undo.default = false
s2s.inbox.post.Undo.Follow = true
# s2s.inbox.shared = true
s2s.collections.custom = false

### Collections support - both spec'ed and custom
collections.default = false
collections.followers = true
collections.following = true
collections.shares = true

### Other AP featuress
# tombstones = true
# Some AP servers don't support standard audience processing


### Other non-AP features
webfinger = true
nodeinfo = true
x-nodeinfo2 = false
host-meta = false
portable_contacts = false # poco
robots_txt = false

#
# Test-specific Configurations
#

# [test_assumes_default_context]
# xfail = "Server exception"
# bug = true